services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:5672"]
        interval: 30s
        timeout: 10s
        retries: 5
    ports:
      - "5672:5672"
    networks:
      - matching-service-net
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - matching-service-net
  api:
    build: .
    ports:
      - 9000:3000
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017
      CLOUDAMQP_URL: amqp://rabbitmq:5672
    networks:
      - matching-service-net
    depends_on:
      - rabbitmq
      - mongo
networks:
  matching-service-net:
    driver: bridge