services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - matching-service-net
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5672"]
        interval: 30s
        timeout: 10s
        retries: 5
    ports:
      - 5672:5672
  websocket-tcp-relay:
    image: cloudamqp/websocket-tcp-relay
    command: --upstream tcp://host.docker.internal:5672
    ports:
      - 15670:15670
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - matching-service-net
  api:
    build: .
    ports:
      - 9000:3000
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      USER_SERVICE_URL: http://host.docker.internal:5346/user-service
      PARKING_LOT_SERVICE_URL: http://host.docker.internal:4000
      RESERVAtion_DURATION_MS: 1800000
    networks:
      - matching-service-net
    depends_on:
      - rabbitmq
      - mongo
    restart: on-failure
networks:
  matching-service-net:
    driver: bridge