services:
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672"
    networks:
      - matching-service-net
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - matching-service-net
  api:
    build: .
    ports:
      - 9000:3000
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    networks:
      - matching-service-net
    depends_on:
      - rabbitmq
      - mongo
    restart: on-failure
networks:
  matching-service-net:
    driver: bridge